apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: {server.port}
      name: http-orderservice
      targetPort: {server.port}
    - protocol: TCP
      port: {server.admin.port}
      name: http-orderservice-admin
      targetPort: {server.admin.port}
