apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: {server.port}
      name: paymentservice
      targetPort: {server.port}
    - protocol: TCP
      port: {server.admin.port}
      name: paymentservice-admin
      targetPort: {server.admin.port}
