apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        version: 1.0.0
    spec:
      containers:
        - name: notification-service
          image: notification-service:1.0.0
          ports:
            - containerPort: 12304
              protocol: TCP
            - containerPort: 12305
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /notification-service/admin/v1/ping
              port: 12305
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /notification-service/admin/v1/ping
              port: 12305
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 30
