apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 12300
      name: http-orderservice
      targetPort: 12300
    - protocol: TCP
      port: 12301
      name: http-orderservice-admin
      targetPort: 12301
