apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        version: {image_version}
    spec:
      containers:
        - name: notification-service
          image: {image_name}
          ports:
            - containerPort: {server.port}
              protocol: TCP
            - containerPort: {server.admin.port}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /notification-service/admin/v1/ping
              port: {server.admin.port}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /notification-service/admin/v1/ping
              port: {server.admin.port}
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 30
